create table If not exists  customer (id bigint  generated by default as identity, balance double, name varchar(255), surname varchar(255), primary key (id));
create table If not exists  sub_account (id bigint  generated by default as identity, balance double, customer_id bigint, primary key (id));
create table If not exists  transaction (id bigint  generated by default as identity, amount double not null, status boolean, transaction_time_stamp timestamp not null, transaction_type varchar(255) not null, customer_id bigint, subaccount_id bigint, primary key (id));
